include: package:lint/analysis_options.yaml

analyzer:
  rules:
    - require_trailing_commas
  exclude:
  #   - packages/**
  # errors:
  #   todo: ignore
  #   avoid_classes_with_only_static_members: ignore
  #   sort_pub_dependencies: ignore
  