name: quizhub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  awesome_dialog: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  # flutter_localizations:
    # sdk: flutter
  # flutter_widget_from_html: ^0.8.5
  get: 4.6.5
  google_fonts: ^2.3.1
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  laravel_exception: ^0.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  url_launcher: ^6.0.3
  shared_preferences: ^2.2.0
  queen:
    git:
      url: https://github.com/FlutterQueen/queen.git
      ref: 19ac2497cec159d6c62bb2fe82123dc688693228
  bottom_navy_bar: ^6.0.0
  pdf: ^3.10.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0



flutter: 
  assets:
    - assets/fonts/STV-Bold.ttf
    - assets/fonts/STV.ttf
    - assets/images/history.png
    - assets/images/logo.png
    - assets/images/teacher.jpeg
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/svg/adults.svg
  uses-material-design: true

