part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const SIGN_IN = _Paths.SIGN_IN;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const TEACHER_HOME = _Paths.TEACHER_HOME;
  static const GRADE_EXERCISES = _Paths.GRADE_EXERCISES;
  static const CREATE_CHOOSE_EXERCISE = _Paths.CREATE_CHOOSE_EXERCISE;
  static const CREATE_FILL_GABS_EXERCISE = _Paths.CREATE_FILL_GABS_EXERCISE;
  static const CREATE_MATCHING_EXERCISE = _Paths.CREATE_MATCHING_EXERCISE;
  static const EDIT_EXERCISE = _Paths.EDIT_EXERCISE;
  static const FINANCIAL_DUES = _Paths.FINANCIAL_DUES;
  static const PARENT_HOME = _Paths.PARENT_HOME;
  static const STUDENT_OVERVIEW = _Paths.STUDENT_OVERVIEW;
  static const ADMIN_HOME = _Paths.ADMIN_HOME;
  static const ADMIN_SCHOOLS_LIST = _Paths.ADMIN_SCHOOLS_LIST;
  static const STUDENT_HOME = _Paths.STUDENT_HOME;
  static const STUDENT_EXERCISES_LIST = _Paths.STUDENT_EXERCISES_LIST;
  static const MCQ_EXERCISE = _Paths.MCQ_EXERCISE;
  static const TEACHER_PAGE = _Paths.TEACHER_PAGE;
  static const COMMENTS_PAGE = _Paths.COMMENTS_PAGE;
  static const QUESTIONS_POSTS = _Paths.QUESTIONS_POSTS;
  static const ENVITATIONS_LIST = _Paths.ENVITATIONS_LIST;
  static const STUDENTS_ENVIT = _Paths.STUDENTS_ENVIT;
  static const TRUE_FALSE_EXERCISE = _Paths.TRUE_FALSE_EXERCISE;
  static const MATCHING_EXERCISE = _Paths.MATCHING_EXERCISE;
  static const TECHER_PAGE = _Paths.TECHER_PAGE;
  static const TECHER_DETAIL = _Paths.TECHER_DETAIL;
  static const COMPLATE_EXERCISE = _Paths.COMPLATE_EXERCISE;
  static const STUDENTS_GRADES = _Paths.STUDENTS_GRADES;
  static const ADMIN_TEACHERS_OF_SCHOOL = _Paths.ADMIN_TEACHERS_OF_SCHOOL;
  static const ADMIN_TEACHER_SUMMERY = _Paths.ADMIN_TEACHER_SUMMERY;
  static const CREATE_TRUE_FALSE_EXERCISE = _Paths.CREATE_TRUE_FALSE_EXERCISE;
  static const SEARCH_FOR_STUDENTS = _Paths.SEARCH_FOR_STUDENTS;
  static const SEARCH_FOR_TEACHERS = _Paths.SEARCH_FOR_TEACHERS;
  static const TEACHER_SUMMERY = _Paths.TEACHER_SUMMERY;
  static const FOLWED_TEACHERS = _Paths.FOLWED_TEACHERS;
  static const ADMIN_ADD_FOLOWERS_ORDERS = _Paths.ADMIN_ADD_FOLOWERS_ORDERS;
  static const ADMIN_GET_MONEY_REQ = _Paths.ADMIN_GET_MONEY_REQ;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const SIGN_IN = '/sign-in';
  static const SIGN_UP = '/sign-up';
  static const TEACHER_HOME = '/teacher-home';
  static const GRADE_EXERCISES = '/grade-exercises';
  static const CREATE_CHOOSE_EXERCISE = '/create-choose-exercise';
  static const CREATE_FILL_GABS_EXERCISE = '/create-fill-gabs-exercise';
  static const CREATE_MATCHING_EXERCISE = '/create-matching-exercise';
  static const EDIT_EXERCISE = '/edit-exercise';
  static const FINANCIAL_DUES = '/financial-dues';
  static const PARENT_HOME = '/parent-home';
  static const STUDENT_OVERVIEW = '/student-overview';
  static const ADMIN_HOME = '/admin-home';
  static const ADMIN_SCHOOLS_LIST = '/admin-schools-list';
  static const STUDENT_HOME = '/student-home';
  static const STUDENT_EXERCISES_LIST = '/student-exercises-list';
  static const MCQ_EXERCISE = '/mcq-exercise';
  static const TEACHER_PAGE = '/teacher-page';
  static const COMMENTS_PAGE = '/comments-page';
  static const QUESTIONS_POSTS = '/questions-posts';
  static const ENVITATIONS_LIST = '/envitations-list';
  static const STUDENTS_ENVIT = '/students-envit';
  static const TRUE_FALSE_EXERCISE = '/true-false-exercise';
  static const MATCHING_EXERCISE = '/matching-exercise';
  static const TECHER_PAGE = '/techer-page';
  static const TECHER_DETAIL = '/techer-detail';
  static const COMPLATE_EXERCISE = '/complate-exercise';
  static const STUDENTS_GRADES = '/students-grades';
  static const ADMIN_TEACHERS_OF_SCHOOL = '/admin-teachers-of-school';
  static const ADMIN_TEACHER_SUMMERY = '/admin-teacher-summery';
  static const CREATE_TRUE_FALSE_EXERCISE = '/create-true-false-exercise';
  static const SEARCH_FOR_STUDENTS = '/search-for-students';
  static const SEARCH_FOR_TEACHERS = '/search-for-teachers';
  static const TEACHER_SUMMERY = '/teacher-summery';
  static const FOLWED_TEACHERS = '/folwed-teachers';
  static const ADMIN_ADD_FOLOWERS_ORDERS = '/admin-add-folowers-orders';
  static const ADMIN_GET_MONEY_REQ = '/admin-get-money-req';
}
